from playwright.sync_api import sync_playwright
p = sync_playwright().start()
b = p.chromium.launch(executable_path=r'C:\Users\PC\AppData\Local\ms-playwright\chromium-1217\chrome-win64\chrome.exe')
page = b.new_page(viewport={'width': 800, 'height': 800})
page.goto('http://localhost:8000/', wait_until='networkidle')
page.click('.menu-toggle')
page.wait_for_timeout(500)
print(page.evaluate('getComputedStyle(document.querySelector("#site-navigation .nav-menu > li > a")).display'))
print(page.evaluate('getComputedStyle(document.querySelector("#site-navigation .nav-menu > li")).display'))
b.close()
p.stop()
