import urllib.request
import re
import json
import os
from html.parser import HTMLParser

def scrape_tempsdance_hero():
    print("Fetching https://tempsdance.fr...")
    req = urllib.request.Request('https://tempsdance.fr', headers={'User-Agent': 'Mozilla/5.0'})
    res = urllib.request.urlopen(req).read().decode('utf-8')

    slider_match = re.search(r'<rs-module-wrap.*?</rs-module-wrap>', res, re.DOTALL)
    if not slider_match:
        print("Could not find slider.")
        return

    slider_html = slider_match.group(0)
    
    # Very basic regex scraping since we can't guarantee bs4 is installed
    slides_html = re.findall(r'<rs-slide.*?</rs-slide>', slider_html, re.DOTALL)
    
    slides = []
    for slide_html in slides_html:
        slide_data = {
            'id': '',
            'bg': '',
            'video': '',
            'layers': []
        }
        
        key_match = re.search(r'data-key="([^"]+)"', slide_html)
        if key_match:
            slide_data['id'] = key_match.group(1)
            
        img_match = re.search(r'<img.*?data-lazyload="([^"]+)".*?>', slide_html, re.DOTALL)
        if img_match:
            slide_data['bg'] = img_match.group(1)
            
        video_match = re.search(r'<rs-bgvideo.*?data-ytid="([^"]+)".*?>', slide_html, re.DOTALL)
        if video_match:
            slide_data['video'] = video_match.group(1)
            
        # extract texts
        layers = re.findall(r'<rs-layer(.*?)</rs-layer>', slide_html, re.DOTALL)
        for layer in layers:
            attrs, content = layer.split('>', 1)
            text = re.sub(r'<[^>]+>', '', content).strip()
            if text:
                slide_data['layers'].append({
                    'type': 'text',
                    'text': text,
                    'is_pink': 'tm-danceslider-text' in attrs
                })
                
        buttons = re.findall(r'<a(.*?)</a>', slide_html, re.DOTALL)
        for btn in buttons:
            attrs, content = btn.split('>', 1)
            text = re.sub(r'<[^>]+>', '', content).strip()
            href_match = re.search(r'href="([^"]+)"', attrs)
            href = href_match.group(1) if href_match else '#'
            if text:
                slide_data['layers'].append({
                    'type': 'button',
                    'text': text,
                    'href': href.replace('https://tempsdance.fr', ''),
                    'is_primary': 'bgc:#ff2a70' in attrs or 'background-color:#ff2a70' in attrs
                })
                
        slides.append(slide_data)

    react_code = """// Generated by scrape_hero.py
"use client";
import React, { useState, useEffect } from 'react';
import Image from 'next/image';
import Link from 'next/link';

export default function HeroSlider() {
  const slides = """ + json.dumps(slides, indent=2) + """;
  const [currentSlide, setCurrentSlide] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % slides.length);
    }, 6000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="hero-slider-wrapper" style={{ position: 'relative', width: '100%', height: 'auto', minHeight: '450px', overflow: 'hidden', backgroundColor: '#000' }}>
      <style>{`
        @keyframes videoFadeIn { 0% { opacity: 0; } 100% { opacity: 1; } }
        @keyframes kenburns { 0% { transform: scale(1); } 100% { transform: scale(1.15); } }
      `}</style>
      
      {slides.map((slide, index) => {
        const isActive = index === currentSlide;
        return (
          <div key={slide.id} style={{
            position: 'absolute', inset: 0,
            opacity: isActive ? 1 : 0,
            visibility: isActive ? 'inherit' : 'hidden',
            transition: 'opacity 1s ease-in-out',
            zIndex: isActive ? 20 : 10
          }}>
            <div style={{ position: 'absolute', inset: 0, overflow: 'hidden' }}>
              <div style={{ position: 'absolute', inset: 0, animation: isActive ? "kenburns 10s ease-out forwards" : "none" }}>
                {slide.bg && (
                  <Image src={slide.bg.startsWith('//') ? 'https:' + slide.bg : slide.bg} alt="bg" fill style={{ objectFit: 'cover' }} priority={index === 0} />
                )}
              </div>
              {slide.video && (
                <iframe
                  src={`https://www.youtube-nocookie.com/embed/${slide.video}?autoplay=1&mute=1&loop=1&playlist=${slide.video}&controls=0&showinfo=0&rel=0`}
                  allow="autoplay; encrypted-media"
                  allowFullScreen
                  style={{ position: "absolute", top: "50%", left: "50%", width: "100%", height: "56.25vw", minHeight: "100%", minWidth: "177.78vh", transform: "translate(-50%, -50%)", border: "none", pointerEvents: "none", opacity: 0, animation: isActive ? "videoFadeIn 1s ease-in 3s forwards" : "none" }}
                />
              )}
              <div style={{ position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,0.45)' }}></div>
            </div>
            
            <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', zIndex: 25, padding: '20px', textAlign: 'center' }}>
              {slide.layers.filter(l => l.type === 'text').map((layer, i) => (
                <div key={i} style={{ 
                  fontFamily: layer.is_pink ? 'Roboto' : 'Oswald', 
                  color: layer.is_pink ? '#ff2a70' : '#ffffff', 
                  fontWeight: layer.is_pink ? 400 : 700, 
                  fontSize: layer.is_pink ? 'clamp(36px, 6vw, 65px)' : 'clamp(24px, 4vw, 40px)', 
                  lineHeight: '1.2', 
                  marginBottom: '10px', 
                  textShadow: '2px 2px 4px rgba(0,0,0,0.5)' 
                }}>
                  {layer.text}
                </div>
              ))}
              
              <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap', justifyContent: 'center', marginTop: '20px' }}>
                {slide.layers.filter(l => l.type === 'button').map((layer, i) => (
                  <Link key={i} href={layer.href} style={{ 
                    backgroundColor: layer.is_primary ? '#ff2a70' : 'transparent', 
                    color: '#ffffff', fontFamily: 'Oswald', fontWeight: 500, fontSize: '14px', 
                    padding: '12px 30px', borderRadius: '6px', textDecoration: 'none', 
                    letterSpacing: '1px', border: layer.is_primary ? 'none' : '1px solid #ffffff', 
                    display: 'inline-flex', alignItems: 'center', transition: 'all 0.3s' 
                  }}>
                    {layer.text} <i className="tm-jassio-icon-right-thin" style={{ marginLeft: "5px" }}></i>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        );
      })}
      
      {/* Navigation Arrows */}
      <div 
        onClick={() => setCurrentSlide((prev) => (prev - 1 + slides.length) % slides.length)}
        style={{ top: "50%", left: "20px", transform: "translateY(-50%)", zIndex: 30, cursor: "pointer", position: "absolute", width: "50px", height: "50px", display: "flex", alignItems: "center", justifyContent: "center", backgroundColor: "#ff2a70", borderRadius: "50%", color: "#fff", transition: "background-color 0.3s", fontSize: "24px" }} 
      >
        &laquo;
      </div>
      <div 
        onClick={() => setCurrentSlide((prev) => (prev + 1) % slides.length)}
        style={{ top: "50%", right: "20px", transform: "translateY(-50%)", zIndex: 30, cursor: "pointer", position: "absolute", width: "50px", height: "50px", display: "flex", alignItems: "center", justifyContent: "center", backgroundColor: "#ff2a70", borderRadius: "50%", color: "#fff", transition: "background-color 0.3s", fontSize: "24px" }} 
      >
        &raquo;
      </div>
    </div>
  );
}
"""

    output_path = os.path.join('app', 'components', 'HeroSliderScraped.js')
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(react_code)
        
    print(f"Generated React component at {output_path}")

if __name__ == "__main__":
    scrape_tempsdance_hero()
